spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OrderDB
    username: postgres
    password: DENNIS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5000

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments




